/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.0 Component Pack 3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter.h>
#include <ADXRS_RATE_aliases.h>
#include <ADXRS_TEMP_aliases.h>
#include <ADXL_X_aliases.h>
#include <ADXL_Y_aliases.h>
#include <POT_ALPHA_aliases.h>
#include <POT_GAIN_aliases.h>
#include <POT_NULL_aliases.h>
#include <POT_TEST_aliases.h>
#include <SPIM_EASYCAMS.h>
#include <ADXRS_CS.h>
#include <ADXRS_CS_aliases.h>
#include <ADXRS_CLK.h>
#include <ADXRS_CLK_aliases.h>
#include <ADC.h>
#include <UART_USB.h>
#include <ANGLE_DAC_aliases.h>
#include <Clock_ENC_1.h>
#include <SPIM_ADXRS.h>
#include <VREF_aliases.h>
#include <VDAC8_GYRO.h>
#include <GYRO_DAC_aliases.h>
#include <ECSPI_CLK.h>
#include <ECSPI_CLK_aliases.h>
#include <Control_Reg_LED.h>
#include <LED_OK.h>
#include <LED_OK_aliases.h>
#include <ADXRS_MOSI.h>
#include <ADXRS_MOSI_aliases.h>
#include <ADXRS_MISO.h>
#include <ADXRS_MISO_aliases.h>
#include <EEPROM.h>
#include <AMuxSeq.h>
#include <isr_CTRL.h>
#include <Clock_CTRL.h>
#include <QuadDec.h>
#include <ENC_A.h>
#include <ENC_A_aliases.h>
#include <ENC_B.h>
#include <ENC_B_aliases.h>
#include <Clock_ENC.h>
#include <ECSPI_CS.h>
#include <ECSPI_CS_aliases.h>
#include <IDAC8_ANGLE.h>
#include <IDAC8_ANGLE_OFFSET.h>
#include <Clock_LED.h>
#include <ECSPI_MOSI.h>
#include <ECSPI_MOSI_aliases.h>
#include <ECSPI_MISO.h>
#include <ECSPI_MISO_aliases.h>
#include <Clock_ENC_2.h>
#include <Counter_LED.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_theACLK.h>
#include <QuadDec_Cnt16.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
