/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <SENSE_IPAN_aliases.h>
#include <SENSE_IPAN.h>
#include <SENSE_VCC_aliases.h>
#include <SENSE_VCC.h>
#include <ADXL_Z_aliases.h>
#include <ADXL_Z.h>
#include <ADXL_Y_aliases.h>
#include <ADXL_Y.h>
#include <ADXL_X_aliases.h>
#include <ADXL_X.h>
#include <ANAPOS_OUTPUT_aliases.h>
#include <ANAPOS_OUTPUT.h>
#include <ADC.h>
#include <UART_USB.h>
#include <VREF_aliases.h>
#include <VREF.h>
#include <Control_Reg_LED.h>
#include <LED_OK_aliases.h>
#include <LED_OK.h>
#include <EEPROM.h>
#include <AMuxSeq.h>
#include <isr_CTRL.h>
#include <Clock_CTRL.h>
#include <Status_Reg_BUTTON.h>
#include <Counter_LED.h>
#include <LED_FAULT_aliases.h>
#include <LED_FAULT.h>
#include <Control_Reg_SYS.h>
#include <V5_PHER_nSHDN_aliases.h>
#include <V5_PHER_nSHDN.h>
#include <V3_nSHDN_aliases.h>
#include <V3_nSHDN.h>
#include <LED_WIFI_OK_aliases.h>
#include <LED_WIFI_OK.h>
#include <LED_WIFI_FAULT_aliases.h>
#include <LED_WIFI_FAULT.h>
#include <SENSE_ITILT_aliases.h>
#include <SENSE_ITILT.h>
#include <HOME_PAN_aliases.h>
#include <HOME_PAN.h>
#include <ADXL_ST_aliases.h>
#include <ADXL_ST.h>
#include <nBUTTON_PUSH_aliases.h>
#include <nBUTTON_PUSH.h>
#include <nBUTTON_CW_aliases.h>
#include <nBUTTON_CW.h>
#include <I2C_COULOMB.h>
#include <I2C_COULOMB_PVT.h>
#include <CC_SDA_aliases.h>
#include <CC_SDA.h>
#include <nBUTTON_CCW_aliases.h>
#include <nBUTTON_CCW.h>
#include <TILT_MOT_FL_aliases.h>
#include <TILT_MOT_FL.h>
#include <Control_Reg_BUZ.h>
#include <BUZ_aliases.h>
#include <BUZ.h>
#include <MOT_SLEEPn_aliases.h>
#include <MOT_SLEEPn.h>
#include <Control_Reg_MOTOR.h>
#include <PAN_MOT_FL_aliases.h>
#include <PAN_MOT_FL.h>
#include <PWM_MOTOR_PAN.h>
#include <PAN_MOT_IN1_aliases.h>
#include <PAN_MOT_IN1.h>
#include <PAN_MOT_IN2_aliases.h>
#include <PAN_MOT_IN2.h>
#include <QuadDec_PAN.h>
#include <QuadDec_PAN_PVT.h>
#include <PAN_ENCA_aliases.h>
#include <PAN_ENCA.h>
#include <PAN_ENCB_aliases.h>
#include <PAN_ENCB.h>
#include <ITG_INT_aliases.h>
#include <ITG_INT.h>
#include <Status_Reg_SYS.h>
#include <BAT_FAULTn_aliases.h>
#include <BAT_FAULTn.h>
#include <BAT_CHRGn_aliases.h>
#include <BAT_CHRGn.h>
#include <TILT_ENCA_aliases.h>
#include <TILT_ENCA.h>
#include <isr_BUTTON.h>
#include <WaveDAC8.h>
#include <Control_Reg_WS.h>
#include <Clock_SYS.h>
#include <QuadDec_TILT.h>
#include <QuadDec_TILT_PVT.h>
#include <Clock_2.h>
#include <VDAC8_ANAPOS.h>
#include <PGA_ASTIM.h>
#include <ASTIM_OUTPUT_aliases.h>
#include <ASTIM_OUTPUT.h>
#include <DEBUG_LED_aliases.h>
#include <DEBUG_LED.h>
#include <isr_Ticks.h>
#include <CC_SCL_aliases.h>
#include <CC_SCL.h>
#include <CC_nALCC_aliases.h>
#include <CC_nALCC.h>
#include <TILT_ENCB_aliases.h>
#include <TILT_ENCB.h>
#include <PWM_MOTOR_TILT.h>
#include <TILT_MOT_IN1_aliases.h>
#include <TILT_MOT_IN1.h>
#include <TILT_MOT_IN2_aliases.h>
#include <TILT_MOT_IN2.h>
#include <Status_Reg_MOTORS.h>
#include <isr_EVENTS_IDENTIF.h>
#include <HOME_TILT_aliases.h>
#include <HOME_TILT.h>
#include <isr_CLU_EXEC.h>
#include <Control_Reg_LORA.h>
#include <IMU_UM7_RX_aliases.h>
#include <IMU_UM7_RX.h>
#include <IMU_UM7_TX_aliases.h>
#include <IMU_UM7_TX.h>
#include <Control_Reg_LORA_RESET.h>
#include <isr_TORQUESTAT.h>
#include <isr_LIMIT_CTRL.h>
#include <isr_FAULT_CTRL.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_IRQ.h>
#include <ADC_theACLK.h>
#include <UART_USB_IntClock.h>
#include <QuadDec_PAN_isr.h>
#include <QuadDec_PAN_Cnt16.h>
#include <WaveDAC8_DacClk.h>
#include <WaveDAC8_Wave1_DMA_dma.h>
#include <WaveDAC8_Wave2_DMA_dma.h>
#include <WaveDAC8_VDAC8.h>
#include <WaveDAC8_BuffAmp.h>
#include <QuadDec_TILT_isr.h>
#include <QuadDec_TILT_Cnt16.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

